import { PaymentType } from '@labour-hiring/enums';

export const dummyJobs = [
  {
    title: 'Frontend Developer',
    companyName: 'TechNova Solutions',
    description:
      'Build responsive web interfaces and reusable components for our growing web applications.',
    location: 'Abuja, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '150000',
    maxPay: '250000',
    minExperienceYears: 1,
    skills: ['React', 'TypeScript', 'CSS'],
  },
  {
    title: 'Backend Developer',
    companyName: 'CloudBridge Technologies',
    description:
      'Develop and maintain REST APIs and backend services for business applications.',
    location: 'Lagos, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '200000',
    maxPay: '350000',
    minExperienceYears: 2,
    skills: ['Node.js', 'NestJS', 'PostgreSQL'],
  },
  {
    title: 'UI UX Designer',
    companyName: 'CreativeHub Africa',
    description:
      'Design intuitive user interfaces and create user experiences for mobile and web products.',
    location: 'Remote',
    paymentType: PaymentType.HOURLY,
    minPay: '5000',
    maxPay: '8000',
    minExperienceYears: 1,
    skills: ['Figma', 'UI Design', 'UX Research'],
  },
  {
    title: 'Mobile App Developer',
    companyName: 'AppWorks Nigeria',
    description:
      'Develop cross-platform mobile applications and integrate them with backend APIs.',
    location: 'Abuja, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '250000',
    maxPay: '450000',
    minExperienceYears: 2,
    skills: ['React Native', 'TypeScript', 'REST API'],
  },
  {
    title: 'Graphic Designer',
    companyName: 'BrandCraft Studio',
    description:
      'Create visual designs for marketing campaigns, social media content, and company branding.',
    location: 'Kaduna, Nigeria',
    paymentType: PaymentType.HOURLY,
    minPay: '3000',
    maxPay: '6000',
    minExperienceYears: 1,
    skills: ['Photoshop', 'Illustrator', 'Branding'],
  },
  {
    title: 'Content Writer',
    companyName: 'WriteWell Media',
    description:
      'Create clear and engaging articles, blog posts, and marketing content for our clients.',
    location: 'Remote',
    paymentType: PaymentType.HOURLY,
    minPay: '2500',
    maxPay: '5000',
    minExperienceYears: 1,
    skills: ['Writing', 'SEO', 'Research'],
  },
  {
    title: 'Digital Marketer',
    companyName: 'MarketPro Agency',
    description:
      'Plan and execute digital marketing campaigns across social media and search platforms.',
    location: 'Lagos, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '120000',
    maxPay: '200000',
    minExperienceYears: 2,
    skills: ['SEO', 'Social Media', 'Google Ads'],
  },
  {
    title: 'Data Analyst',
    companyName: 'Insight Analytics',
    description:
      'Analyze business data and produce reports that help management make informed decisions.',
    location: 'Abuja, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '180000',
    maxPay: '300000',
    minExperienceYears: 2,
    skills: ['Excel', 'SQL', 'Power BI'],
  },
  {
    title: 'Virtual Assistant',
    companyName: 'RemoteAssist',
    description:
      'Provide administrative support including scheduling, email management, and online research.',
    location: 'Remote',
    paymentType: PaymentType.HOURLY,
    minPay: '2000',
    maxPay: '4000',
    minExperienceYears: 0,
    skills: ['Communication', 'Organization', 'Microsoft Office'],
  },
  {
    title: 'SEO Specialist',
    companyName: 'SearchRank Africa',
    description:
      'Improve website visibility through keyword research, technical SEO, and content optimization.',
    location: 'Remote',
    paymentType: PaymentType.FIXED,
    minPay: '100000',
    maxPay: '180000',
    minExperienceYears: 1,
    skills: ['SEO', 'Keyword Research', 'Google Analytics'],
  },
  {
    title: 'WordPress Developer',
    companyName: 'WebForge Studio',
    description:
      'Build and customize WordPress websites based on client requirements and design specifications.',
    location: 'Kaduna, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '100000',
    maxPay: '180000',
    minExperienceYears: 1,
    skills: ['WordPress', 'PHP', 'CSS'],
  },
  {
    title: 'Social Media Manager',
    companyName: 'SocialPulse',
    description:
      'Manage social media accounts, create content calendars, and engage with online communities.',
    location: 'Lagos, Nigeria',
    paymentType: PaymentType.HOURLY,
    minPay: '2500',
    maxPay: '5000',
    minExperienceYears: 1,
    skills: ['Social Media', 'Content Creation', 'Analytics'],
  },
  {
    title: 'Project Manager',
    companyName: 'BuildRight Technologies',
    description:
      'Coordinate development projects, manage deadlines, and communicate with project stakeholders.',
    location: 'Abuja, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '250000',
    maxPay: '400000',
    minExperienceYears: 3,
    skills: ['Project Management', 'Agile', 'Communication'],
  },
  {
    title: 'Customer Support Agent',
    companyName: 'HelpDesk Nigeria',
    description:
      'Respond to customer inquiries and resolve support issues through chat, email, and phone.',
    location: 'Ibadan, Nigeria',
    paymentType: PaymentType.HOURLY,
    minPay: '2000',
    maxPay: '3500',
    minExperienceYears: 0,
    skills: ['Communication', 'Customer Service', 'Problem Solving'],
  },
  {
    title: 'Database Administrator',
    companyName: 'DataCore Systems',
    description:
      'Manage database systems, perform backups, monitor performance, and maintain data security.',
    location: 'Lagos, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '250000',
    maxPay: '450000',
    minExperienceYears: 3,
    skills: ['PostgreSQL', 'MySQL', 'Database Administration'],
  },
  {
    title: 'DevOps Engineer',
    companyName: 'DeployCloud',
    description:
      'Automate deployments and maintain reliable cloud infrastructure for production applications.',
    location: 'Remote',
    paymentType: PaymentType.FIXED,
    minPay: '300000',
    maxPay: '500000',
    minExperienceYears: 2,
    skills: ['Docker', 'AWS', 'CI/CD'],
  },
  {
    title: 'QA Tester',
    companyName: 'QualityFirst Labs',
    description:
      'Test web applications, identify defects, and ensure software meets functional requirements.',
    location: 'Abuja, Nigeria',
    paymentType: PaymentType.HOURLY,
    minPay: '3000',
    maxPay: '6000',
    minExperienceYears: 1,
    skills: ['Manual Testing', 'Test Cases', 'Bug Tracking'],
  },
  {
    title: 'Copywriter',
    companyName: 'WordsMatter Agency',
    description:
      'Write persuasive marketing copy for websites, advertisements, product pages, and campaigns.',
    location: 'Remote',
    paymentType: PaymentType.HOURLY,
    minPay: '3000',
    maxPay: '6000',
    minExperienceYears: 1,
    skills: ['Copywriting', 'Marketing', 'Research'],
  },
  {
    title: 'Video Editor',
    companyName: 'VisualStory Media',
    description:
      'Edit promotional videos, social media content, interviews, and other digital video materials.',
    location: 'Kano, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '80000',
    maxPay: '150000',
    minExperienceYears: 1,
    skills: ['Premiere Pro', 'Video Editing', 'Motion Graphics'],
  },
  {
    title: 'Photographer',
    companyName: 'FocusPoint Studio',
    description:
      'Capture high-quality photographs for events, products, portraits, and promotional campaigns.',
    location: 'Abuja, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '60000',
    maxPay: '120000',
    minExperienceYears: 2,
    skills: ['Photography', 'Lighting', 'Photo Editing'],
  },
  {
    title: 'Electrician',
    companyName: 'BrightHome Services',
    description:
      'Install, maintain, and repair electrical systems in residential and commercial buildings.',
    location: 'Kaduna, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '50000',
    maxPay: '100000',
    minExperienceYears: 2,
    skills: ['Electrical Installation', 'Wiring', 'Maintenance'],
  },
  {
    title: 'Plumber',
    companyName: 'FlowFix Services',
    description:
      'Install and repair water pipes, drainage systems, taps, and other plumbing fixtures.',
    location: 'Abuja, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '45000',
    maxPay: '90000',
    minExperienceYears: 2,
    skills: ['Plumbing', 'Pipe Installation', 'Maintenance'],
  },
  {
    title: 'Bricklayer',
    companyName: 'SolidBuild Construction',
    description:
      'Construct walls and other masonry structures according to building plans and specifications.',
    location: 'Zaria, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '40000',
    maxPay: '80000',
    minExperienceYears: 2,
    skills: ['Bricklaying', 'Masonry', 'Construction'],
  },
  {
    title: 'Carpenter',
    companyName: 'WoodCraft Works',
    description:
      'Build and repair furniture, doors, cabinets, and other wooden structures.',
    location: 'Kaduna, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '50000',
    maxPay: '100000',
    minExperienceYears: 2,
    skills: ['Carpentry', 'Woodworking', 'Furniture Making'],
  },
  {
    title: 'Painter',
    companyName: 'ColorWorks Nigeria',
    description:
      'Prepare and paint interior and exterior surfaces for residential and commercial properties.',
    location: 'Zaria, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '35000',
    maxPay: '70000',
    minExperienceYears: 1,
    skills: ['Painting', 'Surface Preparation', 'Decoration'],
  },
  {
    title: 'Welder',
    companyName: 'MetalWorks Engineering',
    description:
      'Fabricate and repair metal structures using welding equipment and technical drawings.',
    location: 'Kano, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '50000',
    maxPay: '100000',
    minExperienceYears: 2,
    skills: ['Welding', 'Metal Fabrication', 'Safety'],
  },
  {
    title: 'Construction Labourer',
    companyName: 'PrimeBuild Nigeria',
    description:
      'Assist skilled workers with construction activities, material handling, and site preparation.',
    location: 'Abuja, Nigeria',
    paymentType: PaymentType.HOURLY,
    minPay: '1500',
    maxPay: '2500',
    minExperienceYears: 0,
    skills: ['Construction', 'Material Handling', 'Teamwork'],
  },
  {
    title: 'Mason Assistant',
    companyName: 'UrbanBuild Contractors',
    description:
      'Assist masons with mixing materials, carrying supplies, and preparing construction areas.',
    location: 'Kaduna, Nigeria',
    paymentType: PaymentType.HOURLY,
    minPay: '1500',
    maxPay: '2500',
    minExperienceYears: 0,
    skills: ['Construction', 'Masonry', 'Teamwork'],
  },
  {
    title: 'Farm Worker',
    companyName: 'GreenFields Farm',
    description:
      'Assist with planting, harvesting, farm maintenance, and general agricultural activities.',
    location: 'Kaduna, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '40000',
    maxPay: '75000',
    minExperienceYears: 0,
    skills: ['Farming', 'Harvesting', 'Farm Maintenance'],
  },
  {
    title: 'Security Guard',
    companyName: 'SafeGuard Security',
    description:
      'Monitor premises, control access, and ensure the safety of people and property.',
    location: 'Abuja, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '50000',
    maxPay: '90000',
    minExperienceYears: 1,
    skills: ['Security', 'Surveillance', 'Communication'],
  },
  {
    title: 'Driver',
    companyName: 'SwiftMove Logistics',
    description:
      'Transport staff and materials safely while maintaining assigned vehicles and schedules.',
    location: 'Abuja, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '60000',
    maxPay: '110000',
    minExperienceYears: 2,
    skills: ['Driving', 'Navigation', 'Vehicle Maintenance'],
  },
  {
    title: 'Delivery Rider',
    companyName: 'QuickDrop Logistics',
    description:
      'Deliver packages and customer orders efficiently while maintaining accurate delivery records.',
    location: 'Lagos, Nigeria',
    paymentType: PaymentType.HOURLY,
    minPay: '1800',
    maxPay: '3000',
    minExperienceYears: 1,
    skills: ['Motorcycle Riding', 'Navigation', 'Customer Service'],
  },
  {
    title: 'Machine Operator',
    companyName: 'IndustrialWorks Ltd',
    description:
      'Operate production machinery while following safety procedures and production requirements.',
    location: 'Kaduna, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '70000',
    maxPay: '130000',
    minExperienceYears: 2,
    skills: ['Machine Operation', 'Manufacturing', 'Safety'],
  },
  {
    title: 'Warehouse Assistant',
    companyName: 'StockPoint Logistics',
    description:
      'Receive, organize, and dispatch inventory while maintaining accurate stock records.',
    location: 'Lagos, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '50000',
    maxPay: '85000',
    minExperienceYears: 0,
    skills: ['Inventory', 'Warehousing', 'Organization'],
  },
  {
    title: 'Data Entry Clerk',
    companyName: 'DigitalRecords Ltd',
    description:
      'Enter and maintain accurate information in company databases and digital record systems.',
    location: 'Remote',
    paymentType: PaymentType.HOURLY,
    minPay: '2000',
    maxPay: '3500',
    minExperienceYears: 0,
    skills: ['Data Entry', 'Microsoft Excel', 'Typing'],
  },
  {
    title: 'Office Assistant',
    companyName: 'BusinessPoint Ltd',
    description:
      'Support daily office operations including filing, document preparation, and administrative tasks.',
    location: 'Abuja, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '50000',
    maxPay: '90000',
    minExperienceYears: 0,
    skills: ['Administration', 'Microsoft Office', 'Organization'],
  },
  {
    title: 'Accountant',
    companyName: 'FinServe Nigeria',
    description:
      'Maintain financial records, prepare reports, and assist with company accounting activities.',
    location: 'Lagos, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '180000',
    maxPay: '300000',
    minExperienceYears: 2,
    skills: ['Accounting', 'Excel', 'Financial Reporting'],
  },
  {
    title: 'Sales Representative',
    companyName: 'MarketLink Nigeria',
    description:
      'Promote company products, generate leads, and build relationships with potential customers.',
    location: 'Kano, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '70000',
    maxPay: '140000',
    minExperienceYears: 1,
    skills: ['Sales', 'Communication', 'Customer Relations'],
  },
  {
    title: 'Human Resources Assistant',
    companyName: 'PeopleFirst Africa',
    description:
      'Assist with recruitment, employee records, onboarding, and other human resource activities.',
    location: 'Abuja, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '100000',
    maxPay: '180000',
    minExperienceYears: 1,
    skills: ['HR', 'Recruitment', 'Communication'],
  },
  {
    title: 'Business Analyst',
    companyName: 'StrategyWorks',
    description:
      'Analyze business requirements and help teams develop solutions that improve business processes.',
    location: 'Lagos, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '200000',
    maxPay: '350000',
    minExperienceYears: 2,
    skills: ['Business Analysis', 'Requirements Gathering', 'Excel'],
  },
  {
    title: 'Product Designer',
    companyName: 'NextProduct Labs',
    description:
      'Design digital products from initial concepts through detailed interfaces and user testing.',
    location: 'Remote',
    paymentType: PaymentType.FIXED,
    minPay: '180000',
    maxPay: '300000',
    minExperienceYears: 2,
    skills: ['Figma', 'Product Design', 'Prototyping'],
  },
  {
    title: 'Technical Writer',
    companyName: 'DevDocs Africa',
    description:
      'Create technical documentation, API guides, tutorials, and product documentation for developers.',
    location: 'Remote',
    paymentType: PaymentType.HOURLY,
    minPay: '4000',
    maxPay: '7000',
    minExperienceYears: 1,
    skills: ['Technical Writing', 'APIs', 'Documentation'],
  },
  {
    title: 'Cloud Engineer',
    companyName: 'CloudScale Africa',
    description:
      'Deploy and manage scalable cloud infrastructure and support cloud-based applications.',
    location: 'Remote',
    paymentType: PaymentType.FIXED,
    minPay: '300000',
    maxPay: '500000',
    minExperienceYears: 3,
    skills: ['AWS', 'Docker', 'Linux'],
  },
  {
    title: 'Cybersecurity Analyst',
    companyName: 'SecureNet Solutions',
    description:
      'Monitor security systems, investigate incidents, and help protect company infrastructure.',
    location: 'Abuja, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '220000',
    maxPay: '400000',
    minExperienceYears: 2,
    skills: ['Cybersecurity', 'Networking', 'Linux'],
  },
  {
    title: 'Network Technician',
    companyName: 'ConnectIT Nigeria',
    description:
      'Install, configure, and troubleshoot network equipment and connectivity issues.',
    location: 'Kaduna, Nigeria',
    paymentType: PaymentType.HOURLY,
    minPay: '3000',
    maxPay: '6000',
    minExperienceYears: 1,
    skills: ['Networking', 'Cisco', 'Troubleshooting'],
  },
  {
    title: 'Electrical Technician',
    companyName: 'PowerTech Services',
    description:
      'Install, inspect, and maintain electrical equipment and systems in commercial facilities.',
    location: 'Kano, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '80000',
    maxPay: '150000',
    minExperienceYears: 2,
    skills: ['Electrical Systems', 'Maintenance', 'Troubleshooting'],
  },
  {
    title: 'Mechanical Technician',
    companyName: 'MechWorks Industries',
    description:
      'Inspect, maintain, and repair mechanical equipment used in industrial operations.',
    location: 'Kaduna, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '90000',
    maxPay: '160000',
    minExperienceYears: 2,
    skills: ['Mechanical Repair', 'Maintenance', 'Machinery'],
  },
  {
    title: 'Interior Designer',
    companyName: 'SpaceDesign Studio',
    description:
      'Create functional and attractive interior designs for residential and commercial spaces.',
    location: 'Abuja, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '100000',
    maxPay: '200000',
    minExperienceYears: 2,
    skills: ['Interior Design', 'AutoCAD', '3D Design'],
  },
  {
    title: 'Architectural Assistant',
    companyName: 'DesignBuild Architects',
    description:
      'Assist architects with drawings, documentation, models, and preparation of project designs.',
    location: 'Abuja, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '100000',
    maxPay: '180000',
    minExperienceYears: 1,
    skills: ['AutoCAD', 'Architecture', 'SketchUp'],
  },
  {
    title: 'Quantity Surveyor',
    companyName: 'CostBuild Consultants',
    description:
      'Prepare project cost estimates, monitor construction costs, and assist with project budgeting.',
    location: 'Lagos, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '180000',
    maxPay: '300000',
    minExperienceYears: 2,
    skills: ['Quantity Surveying', 'Cost Estimation', 'Construction'],
  },
  {
    title: 'Restaurant Cook',
    companyName: 'TasteHouse Restaurant',
    description:
      'Prepare meals according to restaurant standards while maintaining cleanliness and food safety.',
    location: 'Abuja, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '50000',
    maxPay: '90000',
    minExperienceYears: 1,
    skills: ['Cooking', 'Food Safety', 'Kitchen Management'],
  },
  {
    title: 'Waiter',
    companyName: 'RoyalPlate Restaurant',
    description:
      'Serve customers, take orders, and maintain a clean and welcoming dining environment.',
    location: 'Kaduna, Nigeria',
    paymentType: PaymentType.HOURLY,
    minPay: '1500',
    maxPay: '2500',
    minExperienceYears: 0,
    skills: ['Customer Service', 'Communication', 'Teamwork'],
  },
  {
    title: 'Cleaner',
    companyName: 'CleanSpace Services',
    description:
      'Maintain cleanliness and hygiene across offices, residential buildings, and commercial spaces.',
    location: 'Zaria, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '35000',
    maxPay: '65000',
    minExperienceYears: 0,
    skills: ['Cleaning', 'Organization', 'Time Management'],
  },
  {
    title: 'Gardener',
    companyName: 'GreenGarden Services',
    description:
      'Maintain gardens and outdoor spaces through planting, pruning, watering, and landscaping.',
    location: 'Abuja, Nigeria',
    paymentType: PaymentType.HOURLY,
    minPay: '1800',
    maxPay: '3000',
    minExperienceYears: 1,
    skills: ['Gardening', 'Landscaping', 'Plant Care'],
  },
  {
    title: 'Receptionist',
    companyName: 'FrontDesk Solutions',
    description:
      'Welcome visitors, answer calls, manage appointments, and provide general front desk support.',
    location: 'Lagos, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '60000',
    maxPay: '100000',
    minExperienceYears: 1,
    skills: ['Communication', 'Customer Service', 'Administration'],
  },
  {
    title: 'Marketing Assistant',
    companyName: 'GrowthLab Africa',
    description:
      'Support marketing campaigns through research, content preparation, reporting, and coordination.',
    location: 'Abuja, Nigeria',
    paymentType: PaymentType.FIXED,
    minPay: '80000',
    maxPay: '140000',
    minExperienceYears: 0,
    skills: ['Marketing', 'Research', 'Social Media'],
  },
  {
    title: 'Research Assistant',
    companyName: 'Insight Research Group',
    description:
      'Collect information, analyze research materials, and assist with preparation of research reports.',
    location: 'Zaria, Nigeria',
    paymentType: PaymentType.HOURLY,
    minPay: '2500',
    maxPay: '4500',
    minExperienceYears: 0,
    skills: ['Research', 'Data Analysis', 'Writing'],
  },
];
